// This class is a template for create a new Item object.
// An Item object represents an item generated by the employees working for the factory.
// There are other classes like Payroll, Storage, Employee, Factory for create a factory system with using object-classes.

//Name - Surname: Yasin Alper Bingül
//Number: 170517033

public class Item {
	//Data field of Item class
	private int id;
	public static int numberOfItems;
	
	//Constructor 
	public Item(int id) {
		this.id = id;
		numberOfItems++;
	}
	
	//Methods - Getter and setter methods for private "id" data field
	public int getId() {
		return id;
	}
	
	public void setId(int id) {
		this.id = (id>0) ? id : 0;
	}
	
}
